### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gabriel-maxx** [jussihi/SMM-Rootkit#4]
hello I would like to know if it is compatible with the version of windows 11 22000.376 and also if it is compatible with systems that only support legacy bios?

**Comment by jussihi** [comment]
Hello,

With the recent update https://github.com/jussihi/SMM-Rootkit/commit/bbb79520cb5d2e92e1f0e98672efa3df7a5b72d3, I believe it should be compatible with Windows 11. However, it might report the version to be 10 instead of 11. Please, test the rootkit inside a virtual machine and report back! I don't have windows 11 vm right now so I will not test it for now.

For legacy BIOS systems, I am not sure. You should be able to overwrite a SMM module/driver with the "SmmRootkit.efi" file that is produced when building the OVMF. The rootkit has been tested inside a virtual machine and some Intel's UEFI-based platforms (z370, z390 motherboards).

**Comment by jussihi** [comment]
@NightRaidGamer , does this enlighten you or do you need additional information? I will close the issue if it stays inactive.

**Comment by gabriel-maxx** [comment]
> @NightRaidGamer , does this enlighten you or do you need additional information? I will close the issue if it stays inactive.

I have another question about "shellcode" can it be a Reverse TCP Shellcode? I'm a little confused...

**Comment by jussihi** [comment]
> > @NightRaidGamer , does this enlighten you or do you need additional information? I will close the issue if it stays inactive.
> 
> I have another question about "shellcode" can it be a Reverse TCP Shellcode? I'm a little confused...

Yes it can!

Instead of lines 111-117 in https://github.com/jussihi/SMM-Rootkit/blob/master/shellcode/windows_x64_umd_iat/windows_x64_umd_iat.c, you could *theoretically* and for *educational purposes only* create a reverse TCP shell. To accomplish that, you should modify the `UMD_EXEC_CONTEXT_LIMITED` and `UMD_EXEC_CONTEXT_FULL` to include the needed Windows API functions (some tcp-connection related functionality most likely). Also, you would need to replace the `WinUmdIATShellCode` in the SMMRootkit itself (https://github.com/jussihi/SMM-Rootkit/blob/master/SMM%20Rootkit/SMMRootkit/WinUmdIATHook.c). And of course patch the required functions described above in the SMMRootkit side: https://github.com/jussihi/SMM-Rootkit/blob/master/SMM%20Rootkit/SMMRootkit/WinUmdIATHook.c#L169 onwards.

Hope this helps!

**Comment by gabriel-maxx** [comment]
> > > @NightRaidGamer , does this enlighten you or do you need additional information? I will close the issue if it stays inactive.
> > 
> > 
> > I have another question about "shellcode" can it be a Reverse TCP Shellcode? I'm a little confused...
> 
> Yes it can!
> 
> Instead of lines 111-117 in https://github.com/jussihi/SMM-Rootkit/blob/master/shellcode/windows_x64_umd_iat/windows_x64_umd_iat.c, you could _theoretically_ and for _educational purposes only_ create a reverse TCP shell. To accomplish that, you should modify the `UMD_EXEC_CONTEXT_LIMITED` and `UMD_EXEC_CONTEXT_FULL` to include the needed Windows API functions (some tcp-connection related functionality most likely). Also, you would need to replace the `WinUmdIATShellCode` in the SMMRootkit itself (https://github.com/jussihi/SMM-Rootkit/blob/master/SMM%20Rootkit/SMMRootkit/WinUmdIATHook.c). And of course patch the required functions described above in the SMMRootkit side: https://github.com/jussihi/SMM-Rootkit/blob/master/SMM%20Rootkit/SMMRootkit/WinUmdIATHook.c#L169 onwards.
> 
> Hope this helps!

thanks
